# .github/workflows/self_test.yml
# 这个工作流是作为该项目的自检方案，在github actions中的实测测试。

name: self_test

on: 
    push:
        branches:
        - main

jobs:
    build_test:
        name: 项目构建与测试
        runs-on: macos-latest


        steps:
            - name: 拉取代码
              uses: actions/checkout@v4

            - name: 启用虚拟环境
              run: python3 -m venv .venv

            - name: 安装python依赖
              run: |
                .venv/bin/python -m pip install -r requirements.txt
                echo "依赖下载完毕"

            - name: 测试切换页面
              run: python3 src/actions/switch_windows.py


